### ISSUE TITLE
spi_gpio display-client: cs36 >= max 1

### ISSUE THREAD

**Issue by dreamlayers** [jefflessard/tm16xx-display#3]
On an X92 running Armbian Ubuntu Noble 24.04 with kernel 6.6.67 I could load the module but didn't get the files in /sys. This appeared in dmesg:
```
spi_gpio display-client: cs36 >= max 1
spi_master spi0: spi_device register error /display-client/display-controller@24
spi_master spi0: Failed to create SPI device for /display-client/display-controller@24
```
It seems to be because of  the 24 in the display-controller and reg lines in the dtso:
https://github.com/jefflessard/tm16xx-display/blob/1c2db13323bc38d693b6f0d593636a5e00b55024/devices/x92.dtso#L18-L20
I don't know what that 24 is supposed to mean. Changing both to 0 made the error message go away and made the files appear in /sys.
The error message comes from: https://github.com/torvalds/linux/blob/ffc253263a1375a65fa6c9f62a893e9767fbebfa/drivers/spi/spi.c#L634-L639
The SPI driver sees the 24 as the hexadecimal number of the chip select for that device on that SPI bus. This SPI bus only has 1 chip select, so 0x24 does not make sense. Probably all other dtso files using SPI have the same issue.

**Comment by jefflessard** [comment]
I think address 0x24 of the spi configuration comes from a copy paste from the i2c configuration and would need to be corrected.

Since I don't have an SPI controller to test with, could you try by changing to ``num-chipselects = <0>`` ?

Since there is a single device connected to the SPI, chip select should not be needed at all.

**Comment by jefflessard** [comment]
Thanks for pointing that CS is controlling the STB pin of the controller!

In [Commit 268c207](https://github.com/jefflessard/tm16xx-display/commit/268c207c50cd38ae09816dd7ce5b993b115c5348), I have updated the dtso files using an SPI configuration to use the address 0 instead of 0x24 while keeping `num-chipselects = <1>`. That should fix this issue.
